# Generated by Django 2.2.3 on 2020-07-27 18:51

from django.db import migrations, models
import django.db.models.deletion
import django_pdf2image_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('imageid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('page1', models.FileField(upload_to=django_pdf2image_app.models.user_directory_path)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_pdf2image_app.City')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
